name: Python SoC CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you use pytest, install it
        pip install pytest

    - name: Run SoC tests (unittest)
      run: |
        python -m unittest discover -s . -p "test_soc*.py" -v

    # Optional: if using Pytest
    #- name: Run SoC tests (pytest)
    #  run: pytest -v
